Master
GDSC-RCCIIT/General-Purpose-Scripts pull request #182
Opened 2021-10-04 19:13 UTC by Dr-blue-cyber

# Description

Please include a general summary of the change and/or which issue it fixed. 

Fixes #(issue number)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] New Script (non-breaking change which adds a new script to the repository)
- [ ] This change requires a documentation update

## Has This Been Tested?

- [ ] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)

## Checklist:

- [ ] I have gone through the contributing guidelines before making this Pull Request.
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2021-10-04 21:28 UTC, rijusougata13 commented
hi Please give a  meaning heading of the PR related to your work and also fix linting issue

2021-10-05 02:33 UTC, Dr-blue-cyber commented
hii @rijusougata13 @advaita-saha   all things are working plz check out my PR

2021-10-05 07:18 UTC, Dr-blue-cyber commented
can this PR can not be merge to ?? @OBITORASU

2021-10-06 07:58 UTC, OBITORASU commented on scripts/Secured chat machine/README.md
> +This is WebAPP which provides Secured Chat messaging feaure with Encryption ans decyption security tool.
This is not a webapp but a local gui application

2021-10-06 07:59 UTC, OBITORASU commented on scripts/Secured chat machine/README.md
> +**ChatMachine** is a only suggest how can we achieve our End-to-End encyotion schems thats leads to secures messaging in python application that helps user to maintain our privacy from hackers and th
Fix all the typos here.

2021-10-06 07:59 UTC, OBITORASU requested changes
Left you a review

2021-10-06 09:36 UTC, closed without merging