Adding SMS Sender Script
GDSC-RCCIIT/General-Purpose-Scripts pull request #61
Opened 2021-10-02 08:53 UTC by advaita-saha

# Description

Added the script for sending SMS using the Kaleyra API

Fixes #60 

## Adding the Script for SMS sending and the readme file for further guidance

- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-10-02 09:09 UTC, OBITORASU requested changes
Left a review.

2021-10-02 09:09 UTC, OBITORASU commented on scripts/SMS Sender/README.md
> +* A kaleyra account and api key, secret key
Please document how an user can generate their own api key and use it in the script. Use this [documentation](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/blob/main/scripts/Vaccination-Centre-Locator/README.md) for reference lets say.

2021-10-02 09:09 UTC, OBITORASU commented
Also don't forget to edit the main readme and add your script to the available script table.

2021-10-02 09:27 UTC, advaita-saha commented
@OBITORASU I have made the required changes in the documentation. Please the changes

2021-10-02 09:28 UTC, OBITORASU commented
You need to resolve the merge conflicts before we can merge this PR.

2021-10-02 09:40 UTC, OBITORASU approved these changes
LGTM!

2021-10-02 09:40 UTC, merged

2021-10-03 06:11 UTC, belelaritra commented
@advaita-saha Please change the broken link from [here](https://github.com/GDSC-RCCIIT/General-Purpose-Scripts/blob/main/README.md?plain=1#L43)

2021-10-03 06:15 UTC, OBITORASU commented
Fixed that for him don't worry @belelaritra thanks for the heads up!