Candida18 Contributed a Word Cloud Generator
GDSC-RCCIIT/General-Purpose-Scripts pull request #88
Opened 2021-10-02 17:27 UTC by Candida18

# Description

### Word Cloud Generator
Word Cloud is a data visualization technique used for representing text data in which the size of each word indicates its frequency or importance. Significant textual data points can be highlighted using a word cloud. Word clouds are widely used for analyzing data from social network websites.

## Type of change

- [x] New Script (non-breaking change which adds a new script to the repository)
- [x] This change requires a documentation update

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-10-02 17:38 UTC, OBITORASU commented
Fix the merge conflict. Also add the linked issue in the PR description like this fixes #(issue number).

2021-10-02 17:39 UTC, OBITORASU commented on scripts/Word-Cloud-Generator/Bitcoin.txt
> +These characteristics make Bitcoin fundamentally different from a fiat currency, which is backed by the full faith and credit of its government. Fiat currency issuance is a highly centralized activit
Have this file removed.

2021-10-02 17:40 UTC, OBITORASU commented on scripts/Word-Cloud-Generator/READme.md
> +<p align="justify">Word Cloud is a data visualization technique used for representing text data in which the size of each word indicates its frequency or importance. Significant textual data points c
Please add some documentation on how to run your script.

2021-10-02 17:42 UTC, OBITORASU commented
Move your `.png` file to a dedicated images directory under your script directory. Also could you please convert your `.ipynb` file to a `.py` file? This [post](https://stackoverflow.com/questions/35545402/how-to-run-an-ipynb-jupyter-notebook-from-terminal) can help you with that, read the second answer.

2021-10-03 04:45 UTC, OBITORASU requested changes
Fix the merge conflict and check the other comments I left above.

2021-10-03 10:57 UTC, OBITORASU commented
Could you please convert the `.ipynb` file in a `.py` file?

2021-10-03 11:17 UTC, OBITORASU commented
Looks good just fix the merge conflict.

2021-10-03 16:45 UTC, rijusougata13 commented
hi, also add a screenshot in the PR

2021-10-04 06:19 UTC, Candida18 commented
> Fix the merge conflict and check the other comments I left above.

I have made the changes. Please close this comment

2021-10-04 08:19 UTC, rijusougata13 commented
Looks good ! Please resolve the conflict. I'll merge the PR

2021-10-04 08:29 UTC, rijusougata13 commented on scripts/Word-Cloud-Generator/Word_Cloud.py
> +"""
also put this instruction in readme so end user can find out whats to install. Change this and your PR is ready to merge

2021-10-04 08:54 UTC, rijusougata13 commented
great work !!

2021-10-04 08:54 UTC, merged

2021-10-04 09:32 UTC, Candida18 commented
> great work !!

Please add the necessary labels especially the `hacktoberfest-accepted` label. Since I've worked so hard.

2021-10-04 09:51 UTC, OBITORASU commented
@Candida18 the label is not needed for your PR to count. Any PR which is merged counts towards your progress.

From Hacktoberfest 2021 FAQ, Rules section FAQ number 13
```
Your pull requests will count toward your participation if they are in a repository with the 'hacktoberfest 'topic and once they have been merged, approved by a maintainer or labeled as **hacktoberfest-accepted**. 


Additionally, any pull request with the **hacktoberfest-accepted** label, submitted to any public GitHub/GitLab repository, with or without the hacktoberfest topic, will be considered valid for Hacktoberfest.
```

2021-10-04 12:01 UTC, rijusougata13 commented
> > great work !!
> 
> Please add the necessary labels especially the `hacktoberfest-accepted` label. Since I've worked so hard.

Please wait couple of hours and you can find that progress in your hacktoberfest profile.