Ocr script
GDSC-RCCIIT/General-Purpose-Scripts pull request #98
Opened 2021-10-02 20:24 UTC by Harshil-Jani

# Description

This PR is about an OCR Scanner that takes the images which are less noisy and scan them and produce the text output if any text is present in separate file.

Fixes #66 

## Type of change

Please delete options that are not relevant.

- [x] New Script (non-breaking change which adds a new script to the repository)

## Has This Been Tested?

- [x] I confirm that I have tested my script locally and verified that it works as intended.

## Screenshot (if applicable)

Image to be scanned (Screenshot from Hacktoberfest site)

![image_01](https://user-images.githubusercontent.com/79367883/135729439-39b0aaf1-809e-44bc-bfeb-b589978f14d9.png)

Output :

![image](https://user-images.githubusercontent.com/79367883/135729489-85c512dd-6b58-4dad-bc03-af707a086049.png)

## Checklist:

- [x] I have gone through the contributing guidelines before making this Pull Request.
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-10-02 20:26 UTC, Harshil-Jani commented
@OBITORASU Can you guide me what checks are failing ? So that I can make changes accordingly

2021-10-02 20:29 UTC, OBITORASU commented
You have to install black autolinter locally with `pip install black`. Then run `black .` in the root directory of your script. Black will do all the formatting for you just commit and push the changes made by black.

2021-10-03 03:13 UTC, OBITORASU commented on scripts/OCR_Scanner/ocr.py
> +filename = 'https://github.com/Harshil-Jani/General-Purpose-Scripts/blob/OCR-Script/scripts/OCR_Scanner/image_01.png'
Make an input field allowing the user to choose a valid file instead of having to edit the script.

2021-10-03 03:13 UTC, OBITORASU requested changes

2021-10-03 03:13 UTC, OBITORASU commented on scripts/OCR_Scanner/ocr.py
> +with open("https://github.com/Harshil-Jani/General-Purpose-Scripts/blob/OCR-Script/scripts/OCR_Scanner/ocr.txt","w") as f:
Use yet another input field to allow the user to select the save location for the output.

2021-10-03 05:54 UTC, Harshil-Jani reviewed
Self Check done

2021-10-03 05:55 UTC, OBITORASU commented on scripts/OCR_Scanner/ocr.py
> +    f.close()
Can you validate if the entered path is a valid one?

2021-10-03 05:55 UTC, OBITORASU commented on scripts/OCR_Scanner/ocr.py
> +content = text
Use a try except to catch exceptions in case the image path is invalid or the image itself is invalid

2021-10-03 05:55 UTC, OBITORASU requested changes
Left a review

2021-10-03 06:08 UTC, OBITORASU requested changes
Please edit the main readme and add your script to the list

2021-10-03 06:10 UTC, Harshil-Jani commented
> Please edit the main readme and add your script to the list

I have one doubt regarding that ! Untill the scripts get merged how can I get the link of GDSC-RCCIIT repo where my files will be stored. As of now I can just add the link from my fork right?

2021-10-03 06:16 UTC, OBITORASU commented
Replace your name with GDSC-RCCIIT yep you got it right!

2021-10-04 12:58 UTC, Harshil-Jani commented
@OBITORASU Can you guide what can i do to resolve conflicts ?

2021-10-04 17:17 UTC, OBITORASU commented
@Harshil-Jani you can watch this [video](https://youtu.be/xNVM5UxlFSA) for reference.

2021-10-05 06:33 UTC, Harshil-Jani commented
@OBITORASU Hey ! Actually the thing is in README.md even if i resolve conflicts, then if you merge other PRs by that time then my README commits will keep on conflicting. 😅. So, How can we deal with this ?  I researched somewhat and it says that the one who is maintaining the repo gets options to merge and resolve conflict. If I will do from my side then it will keep conflicting with other Merged PR's Readme edits. Can you help out with this? I am once again changing the conflict by changing my entry in README.

2021-10-05 06:37 UTC, Harshil-Jani commented
If now before this PR being merged if anyone will enter their entry in line 37 then it will conflict ! Can you plz merge it soon So other person can fetch their fork upstream and then everything will be even.

2021-10-05 07:14 UTC, OBITORASU commented
Add the requirements.txt and I will have this merged asap.

2021-10-05 08:25 UTC, OBITORASU commented
Thank you!

2021-10-05 08:25 UTC, OBITORASU approved these changes

2021-10-05 08:25 UTC, merged